### ISSUE TITLE
vnpy_mongodb.py 在写入tick overview 时， count 错误调用了bar_collection.count_documents( )

### ISSUE THREAD

**Issue by tinyi2018** [vnpy/vnpy_mongodb#13]
vnpy_mongodb.py 的第 231行， 在写入tick overview 时， overview["count"]  = 错误调用bar 的collection 的
 bar_collection.count_documents( )， 应用调用 tick_collection.count_documents( ).

![屏幕截图 2023-09-21 211159](https://github.com/vnpy/vnpy_mongodb/assets/92707615/385a0b9c-b6cd-4a1a-8f11-a432a675720b)

**Comment by vnpy** [comment]
已修复
